package br.com.unipatas.view.animal;

import br.com.unipatas.controller.AnimalController;
import br.com.unipatas.model.Animal;
import javafx.geometry.*; import javafx.scene.control.*; import javafx.scene.control.cell.PropertyValueFactory; import javafx.scene.layout.*; import java.util.List;

public class AnimalObjetosView extends BorderPane {
  private final TabPane tabPane; private final Tab tabCadastro; private final Tab tabAtualizar; private AnimalController controller; private TilePane cards; private TableView<Animal> tabela;
  public AnimalObjetosView(TabPane tabPane, Tab tabCadastro, Tab tabAtualizar) { this.tabPane=tabPane; this.tabCadastro=tabCadastro; this.tabAtualizar=tabAtualizar; getStyleClass().add("objetos-page"); try{controller=new AnimalController();}catch(Exception e){alerta(Alert.AlertType.ERROR,"Erro","Erro ao conectar ao banco.");} montar(); }
  private void montar(){ VBox conteudo=new VBox(18); conteudo.setPadding(new Insets(26)); Label badge=new Label("ANIMAIS"); badge.getStyleClass().add("objetos-badge"); Label titulo=new Label("Animais cadastrados"); titulo.getStyleClass().add("objetos-titulo"); Label sub=new Label("Cards padronizados para consulta rápida dos animais do sistema."); sub.getStyleClass().add("objetos-subtitulo"); cards=new TilePane(); cards.setHgap(16); cards.setVgap(16); cards.setPrefColumns(3); ScrollPane scroll=new ScrollPane(cards); scroll.setFitToWidth(true); scroll.setHbarPolicy(ScrollPane.ScrollBarPolicy.NEVER); scroll.getStyleClass().add("cards-scroll"); VBox.setVgrow(scroll,Priority.ALWAYS); conteudo.getChildren().addAll(badge,titulo,sub,scroll); setCenter(conteudo); Button btnNovo=new Button("+"); btnNovo.getStyleClass().add("fab"); btnNovo.setOnAction(e->tabPane.getSelectionModel().select(tabCadastro)); StackPane fab=new StackPane(btnNovo); fab.setAlignment(Pos.BOTTOM_RIGHT); fab.setPadding(new Insets(0,26,26,0)); setBottom(fab); carregarCards(); }
  private void carregarCards(){ cards.getChildren().clear(); try{ List<Animal> lista=controller.listarTodos(); if(lista.isEmpty()){cards.getChildren().add(estadoVazio("Nenhum animal cadastrado","Clique no + para cadastrar.")); return;} for(Animal a:lista)cards.getChildren().add(card("#"+a.getId(),a.getNome(),a.getRaca()+" • "+a.getPorte(),"Abrigo #"+a.getIdAbrigo()+" • "+a.getPeso()+" kg")); }catch(Exception e){alerta(Alert.AlertType.ERROR,"Erro",e.getMessage());}}
  private VBox card(String id,String titulo,String info1,String info2){ VBox c=new VBox(8); c.getStyleClass().add("objeto-card"); c.setPrefWidth(250); Label lid=new Label(id); lid.getStyleClass().add("objeto-card-id"); Label lt=new Label(titulo); lt.getStyleClass().add("objeto-card-titulo"); Label l1=new Label(info1); l1.getStyleClass().add("objeto-card-info"); Label l2=new Label(info2); l2.getStyleClass().add("objeto-card-info"); c.getChildren().addAll(lid,lt,l1,l2); return c; }
  private VBox estadoVazio(String titulo,String texto){ VBox v=new VBox(8,new Label("🐶"),new Label(titulo),new Label(texto)); v.setAlignment(Pos.CENTER); v.getStyleClass().add("estado-vazio-card"); return v; }
  public BorderPane getGerenciamento(){ BorderPane painel=new BorderPane(); painel.getStyleClass().add("objetos-page"); painel.setPadding(new Insets(24)); VBox topo=new VBox(6); Label titulo=new Label("Gerenciar animais"); titulo.getStyleClass().add("objetos-titulo"); Label sub=new Label("Tabela de busca com editar e excluir na própria linha."); sub.getStyleClass().add("objetos-subtitulo"); topo.getChildren().addAll(titulo,sub); tabela=new TableView<>(); tabela.getStyleClass().add("tabela-gerenciamento"); TableColumn<Animal,Void> acoes=colunaAcoes(); acoes.setPrefWidth(170); TableColumn<Animal,Integer> id=new TableColumn<>("ID"); id.setCellValueFactory(new PropertyValueFactory<>("id")); id.setPrefWidth(70); TableColumn<Animal,String> nome=new TableColumn<>("Nome"); nome.setCellValueFactory(new PropertyValueFactory<>("nome")); nome.setPrefWidth(170); TableColumn<Animal,String> raca=new TableColumn<>("Raça"); raca.setCellValueFactory(new PropertyValueFactory<>("raca")); raca.setPrefWidth(150); TableColumn<Animal,String> porte=new TableColumn<>("Porte"); porte.setCellValueFactory(new PropertyValueFactory<>("porte")); porte.setPrefWidth(110); tabela.getColumns().addAll(acoes,id,nome,raca,porte); atualizarTabela(); VBox box=new VBox(16,topo,tabela); VBox.setVgrow(tabela,Priority.ALWAYS); painel.setCenter(box); return painel; }
  private TableColumn<Animal,Void> colunaAcoes(){ TableColumn<Animal,Void> col=new TableColumn<>("Ações"); col.setCellFactory(p->new TableCell<>(){ Button editar=new Button("Editar"); Button excluir=new Button("Excluir"); HBox box=new HBox(8,editar,excluir); {editar.getStyleClass().add("botao-tabela-editar"); excluir.getStyleClass().add("botao-tabela-excluir"); editar.setOnAction(e->editar(getTableView().getItems().get(getIndex()))); excluir.setOnAction(e->excluir(getTableView().getItems().get(getIndex())));} @Override protected void updateItem(Void item,boolean empty){super.updateItem(item,empty); setGraphic(empty?null:box);}}); return col; }
  private void editar(Animal a){ tabAtualizar.setContent(new AnimalAtualizarView(a.getId()).getConteudo()); tabPane.getSelectionModel().select(tabAtualizar); }
  private void excluir(Animal a){ if(confirmar("Excluir animal","Deseja excluir "+a.getNome()+"?")){try{controller.deletar(a.getId()); atualizarTabela(); carregarCards();}catch(Exception e){alerta(Alert.AlertType.ERROR,"Erro",e.getMessage());}} }
  private void atualizarTabela(){ try{tabela.getItems().setAll(controller.listarTodos());}catch(Exception e){alerta(Alert.AlertType.ERROR,"Erro",e.getMessage());} }
  private boolean confirmar(String t,String txt){ Alert a=new Alert(Alert.AlertType.CONFIRMATION,txt,ButtonType.CANCEL,ButtonType.OK); a.setTitle(t); a.setHeaderText(null); return a.showAndWait().orElse(ButtonType.CANCEL)==ButtonType.OK; }
  private void alerta(Alert.AlertType tipo,String t,String txt){ Alert a=new Alert(tipo); a.setTitle(t); a.setHeaderText(null); a.setContentText(txt); a.showAndWait(); }
}
